language: c

notifications:
  email: false

before_script:
# travis has changed to 64-bit and we require 32-bit compatibility libraries
  - "sudo apt-get update && sudo apt-get install python-tk"

  - "sudo apt-get install scons"

  - "sudo apt-get -qq install gcc-multilib libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 libsdl-dev || true"

  - cd .. && BASE_ROOT=$(pwd) && mkdir packages_temp && mv packages packages_temp && cd packages_temp && echo "source \"\$PKGS_DIR/packages/Kconfig\"" > Kconfig
  
  - "cd ${BASE_ROOT} && export PKGS_ROOT=${BASE_ROOT}/packages_temp && git clone --depth=1 --branch=master https://github.com/RT-Thread/rt-thread.git rt-thread && export RTT_ROOT=${BASE_ROOT}/rt-thread || true"

  - "cd ${RTT_ROOT}/tools/kconfig-frontends && scons || true"
  
  - "cd ${RTT_ROOT}/bsp/qemu-vexpress-a9 && sudo ../../tools/kconfig-frontends/kconfig-mconf Kconfig -n"

  - "cd ${PKGS_ROOT}/packages && python ci.py"
  
script:

  echo success

